### ISSUE TITLE
[Request] Pre-Packed Chrome Extension

### ISSUE THREAD

**Issue by hasbrowow** [feracommerce/shopify_app_detector#2]
Super useful app!

To get it visible I suggest adding a pre-packed Chrome extension which we can then post on the Shopify forums and Shopify Plus Facebook Group.

**Comment by jayelkaake** [comment]
We were just waiting for it to get approved. It just got approved today:
https://chrome.google.com/webstore/detail/feraai-shopify-app-detect/lhfdhjladfcmghahdbcmlceajdlbkale

**BTW please give it 5-stars and a quick review** so people know it's not a scam or something.
