### ISSUE TITLE
Turbo Themes Not Detected

### ISSUE THREAD

**Issue by jayelkaake** [feracommerce/shopify_app_detector#36]
The [Turbo themes](https://outofthesandbox.com/products/turbo-theme-portland) don't seem to be getting detected.  We should figure out why and fix that.

**Comment by Qoraiche** [comment]
can you please fix it! thank you

**Comment by jayelkaake** [comment]
Resolved this in the latest version 0.6.2 which I am going to deploy now and submit to the app store.
